---
title: "Exploratory data analysis"
format: html
editor: source
---

## load the libraries

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(readxl)
```

## load the data

```{r}
wdi_raw <- read_excel(here::here("data/WDI_EXCEL/WDIEXCEL.xlsx"), sheet = "Data")

africa <- read_csv(here::here("data/africa - overview.csv"))
```

**Filter the World Development Indicators (WDI) data for African countries**

```{r}
# filter only for the African countries
africa_wdi <- wdi_raw %>% 
  right_join(
    africa %>% select(!`Country Name`), 
    by = join_by("Country Code" == "Country Code")
  ) 
```

## Wrangling and exploration

```{r}
africa_wdi <- africa_wdi %>% 
  pivot_longer(cols = "1960":"2023", names_to = "year", values_to = "value")
```


Filter for the indicators that will be in the app 

```{r}
indicators <- c(
  "Population, total",
  "GDP per capita (current US$)"
)

africa_wdi <- africa_wdi %>% 
  filter(`Indicator Name` %in% indicators, year == "2022") %>% 
  select(!c("Indicator Code", "year")) %>% 
  pivot_wider(names_from = `Indicator Name`, values_from = value)
```

Split the currency

```{r}
africa_wdi <- africa_wdi %>% 
  mutate(Currency = gsub("\\s*\\(([^)]+)\\)", ", \\1", Currency)) %>% 
  separate_wider_delim(Currency, names = c("Currency", "Currency Code"), delim = ",")
```

Rename the columns to make it easy to work with

```{r}
africa_wdi <- africa_wdi %>% 
  rename(
    country_name = `Country Name`,
    country_code = `Country Code`,
    capital = Capital,
    currency = Currency,
    currency_code = `Currency Code`,
    country_profile = `Country Profile`,
    gdp_per_capita = `GDP per capita (current US$)`,
    population_total = `Population, total`
  )
```


Save the africa data set

```{r}
write_csv(africa_wdi, here::here("data/africa.csv")) 
```

